Content-Type: multipart/mixed; boundary="===============0856568850714492334=="
MIME-Version: 1.0
Message-ID: <170487859528.24916.16043298868754979268@fit.hcmus.edu.vn>
Date: Wed, 10 Jan 2024 16:23:15 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <tqtuyen.deptrai@fit.hcmus.edu.vn>
Subject: hello world

--===============0856568850714492334==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

aGlwcm8gcG9y

--===============0856568850714492334==--