Content-Type: multipart/mixed; boundary="===============6705103156423847710=="
MIME-Version: 1.0
Message-ID: <170487901173.17072.14773503140127608326@fit.hcmus.edu.vn>
Date: Wed, 10 Jan 2024 16:30:11 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <tqtuyen.deptrai@fit.hcmus.edu.vn>
Subject: hello

--===============6705103156423847710==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

ZmRoc2FmOw==

--===============6705103156423847710==
MIME-Version: 1.0
Content-Type: application/octet-stream; name="github.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="github.txt"

LSB04bqhbyAxIHByb2plY3QgdHLDqm4gZ2l0aHViIHbDoCDEkeG6qXkgbMOqbiBnaXRodWINCjEu
IHThuqFvIDEgZ2l0aHViIHJlcG9zaXRvcnkgKGZvbGRlcikgLSBuxqFpIGNo4bupYSBjb2RlDQoy
LiBjbG9uZSBwcm9qZWN0IG7DoHk6IGdpdCBjbG9uZSBsaW5rX3lvdXJfcmVwb3NpdG9yeQ0KMy4g
dmnhur90IGNvZGUNCjQuIGdpdCBzdGF0dXMgKGtp4buDbSB0cmEgdHLhuqFuZyB0aMOhaSBmaWxl
cykNCjUuIGdpdCBhZGQgLiAodGjDqm0gdOG6pXQgY+G6oyBjw6FjIGZpbGVzKQ0KNi4gZ2l0IGNv
bW1pdCAtbSAieW91cl9tZXNzYWdlIiAodOG6oW8gbuG7mWkgZHVuZyBjb21taXQpDQo3LiBnaXQg
cHVzaCBvcmlnaW4gbWFpbg0KDQotIHThuqFvIHByb2plY3QgbG9jYWwgdsOgIMSR4bqpeSBsw6pu
IGdpdGh1Yg0KMS4gZ2l0IGluaXQNCjIuIGdpdCBzdGF0dXMNCjMuIGdpdCBhZGQgLg0KNC4gZ2l0
IGNvbW1pdCAtbSAieW91cl9tZXNzYWdlIg0KNS4gZ2l0IHJlbW90ZSBhZGQgb3JpZ2luIGxpbmtf
eW91cl9yZXBvc2l0b3J5DQo2LiBnaXQgcHVzaCBvcmlnaW4gbWFzdGVyDQoNCg0KLSBsw6BtIHZp
4buHYyBuaMOzbSANCjEuIGdpdCBwdWxsID0gZ2l0IGZldGNoICsgZ2l0IG1lcmdlIChr4bq/dCBo
4bujcCBmaWxlIHRyb25nIG3DoXkgdsOgIGZpbGUgdHLDqm4gZ2l0aHViIHbhu4EpDQoyLiBnaXQg
bWVyZ2UgKGfhu5lwIDIgYnJhbmNoIHbDoG8pDQozLiBnaXQgY29uZmxpY3QgKHjhuqN5IHJhIGto
aSB4dW5nIMSR4buZdCwga2jDtG5nIG1lcmdlIMSRxrDhu6NjKQ0KNC4gZ2l0IGNoZWNrb3V0IGJy
YW5jaC9jb21taXQgKGNodXnhu4NuIG5ow6FuaCkNCg0K

--===============6705103156423847710==--