Content-Type: multipart/mixed; boundary="===============0130163349453552683=="
MIME-Version: 1.0
Message-ID: <170369254362.22132.863261024917443957@testing.com>
Date: Wed, 27 Dec 2023 22:55:43 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: 
Cc: tqtuyen.deptrai@fit.hcmus.edu.vn
From: Ahihi do ngoc <ahihi@testing.com>
Subject: test test 2

--===============0130163349453552683==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test nua
--===============0130163349453552683==--