Content-Type: multipart/mixed; boundary="===============2311401958266357426=="
MIME-Version: 1.0
Message-ID: <170369264085.11924.2860352070789497914@testing.com>
Date: Wed, 27 Dec 2023 22:57:20 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: 
From: Ahihi do ngoc <ahihi@testing.com>
Subject: test 3

--===============2311401958266357426==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test ets
--===============2311401958266357426==--