Content-Type: multipart/mixed; boundary="------------Um6hMKaQl05c6zOcmtb5RY8G"
Message-ID: <6984f9fb-5353-4c9d-a404-3aab9ad08888@testing.com>
Date: Sat, 16 Dec 2023 22:37:50 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <ahihi@testing.com>
Subject: virus ASAP

This is a multi-part message in MIME format.
--------------Um6hMKaQl05c6zOcmtb5RY8G
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

meeting

--------------Um6hMKaQl05c6zOcmtb5RY8G
Content-Type: text/plain; charset=UTF-8; name="github.txt"
Content-Disposition: attachment; filename="github.txt"
Content-Transfer-Encoding: base64

LSB04bqhbyAxIHByb2plY3QgdHLDqm4gZ2l0aHViIHbDoCDEkeG6qXkgbMOqbiBnaXRodWIN
CjEuIHThuqFvIDEgZ2l0aHViIHJlcG9zaXRvcnkgKGZvbGRlcikgLSBuxqFpIGNo4bupYSBj
b2RlDQoyLiBjbG9uZSBwcm9qZWN0IG7DoHk6IGdpdCBjbG9uZSBsaW5rX3lvdXJfcmVwb3Np
dG9yeQ0KMy4gdmnhur90IGNvZGUNCjQuIGdpdCBzdGF0dXMgKGtp4buDbSB0cmEgdHLhuqFu
ZyB0aMOhaSBmaWxlcykNCjUuIGdpdCBhZGQgLiAodGjDqm0gdOG6pXQgY+G6oyBjw6FjIGZp
bGVzKQ0KNi4gZ2l0IGNvbW1pdCAtbSAieW91cl9tZXNzYWdlIiAodOG6oW8gbuG7mWkgZHVu
ZyBjb21taXQpDQo3LiBnaXQgcHVzaCBvcmlnaW4gbWFpbg0KDQotIHThuqFvIHByb2plY3Qg
bG9jYWwgdsOgIMSR4bqpeSBsw6puIGdpdGh1Yg0KMS4gZ2l0IGluaXQNCjIuIGdpdCBzdGF0
dXMNCjMuIGdpdCBhZGQgLg0KNC4gZ2l0IGNvbW1pdCAtbSAieW91cl9tZXNzYWdlIg0KNS4g
Z2l0IHJlbW90ZSBhZGQgb3JpZ2luIGxpbmtfeW91cl9yZXBvc2l0b3J5DQo2LiBnaXQgcHVz
aCBvcmlnaW4gbWFzdGVyDQoNCg0KLSBsw6BtIHZp4buHYyBuaMOzbSANCjEuIGdpdCBwdWxs
ID0gZ2l0IGZldGNoICsgZ2l0IG1lcmdlIChr4bq/dCBo4bujcCBmaWxlIHRyb25nIG3DoXkg
dsOgIGZpbGUgdHLDqm4gZ2l0aHViIHbhu4EpDQoyLiBnaXQgbWVyZ2UgKGfhu5lwIDIgYnJh
bmNoIHbDoG8pDQozLiBnaXQgY29uZmxpY3QgKHjhuqN5IHJhIGtoaSB4dW5nIMSR4buZdCwg
a2jDtG5nIG1lcmdlIMSRxrDhu6NjKQ0KNC4gZ2l0IGNoZWNrb3V0IGJyYW5jaC9jb21taXQg
KGNodXnhu4NuIG5ow6FuaCkNCg0K

--------------Um6hMKaQl05c6zOcmtb5RY8G--