Content-Type: multipart/mixed; boundary="===============5923240781345673512=="
MIME-Version: 1.0
Message-ID: <170487865829.24916.11644261025890819207@fit.hcmus.edu.vn>
Date: Wed, 10 Jan 2024 16:24:18 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <tqtuyen.deptrai@fit.hcmus.edu.vn>
Subject: hipre fdasf

--===============5923240781345673512==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

Zmhkc2pmZCByZXBvcnQ=

--===============5923240781345673512==--