Content-Type: multipart/mixed; boundary="===============5803534068497899509=="
MIME-Version: 1.0
Message-ID: <170487803950.20544.13569151738445481010@fit.hcmus.edu.vn>
Date: Wed, 10 Jan 2024 16:13:59 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <tqtuyen.deptrai@fit.hcmus.edu.vn>
Subject: report

--===============5803534068497899509==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

aGVsbGxv

--===============5803534068497899509==--