Content-Type: multipart/mixed; boundary="===============3816018438443182246=="
MIME-Version: 1.0
Message-ID: <170487884797.5160.7347069942986732027@fit.hcmus.edu.vn>
Date: Wed, 10 Jan 2024 16:27:27 +0700
User-Agent: Fast-Mailer
Content-Language: en-US
To: tqtuyen.deptrai@fit.hcmus.edu.vn
From: ahihi <tqtuyen.deptrai@fit.hcmus.edu.vn>
Subject: heijffdsf 

--===============3816018438443182246==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

ZmhkanNha2YgY3JhY2sgZmhkamFzZmtmZHM/Zmpka2E7Lw==

--===============3816018438443182246==--